name: Build and Push to IPFS

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build and Push to IPFS
        run: |
          docker build -t lunaria:latest .
